version: 0.2

phases:
  install:
    commands:
      - echo "Installing dependencies..."

  pre_build:
    commands:
      - echo "Preparing deployment..."

  build:
    commands:
      - echo "Building project..."

  post_build:
    commands:
      - echo "Build completed."

artifacts:
  files:
    - '**/*'